### ISSUE TITLE
Escape attributes before printing

### ISSUE THREAD

**Issue by oliverpool** [a-h/htmlformat#1]
As noticed in https://github.com/a-h/templ/pull/284
```go
 // &lt; & co. gets wrongly removed
htmlformat.Fragment(&buf, strings.NewReader(`<button class="&lt;script&gt; &#34; href=&#34;#hacked">Escaped classes</button>`))
```

`a.Val` must be escaped using `html.EscapeString` in at least two places:
https://github.com/a-h/htmlformat/blob/c3d4a33d8ada426554c3f42f92cf139c4a742fdd/format.go#L63
https://github.com/a-h/htmlformat/blob/c3d4a33d8ada426554c3f42f92cf139c4a742fdd/format.go#L133

**Comment by a-h** [comment]
Ah, you're right. Thanks!

Unfortunately, I don't think it's as simple as just re-escaping the `a.Val`, because if the attribute value is already invalid, e.g. `class="&"`, running it through `html.EscapeString` will "fix" it so that the output is `class="&amp;"`. 
This was discussed  https://github.com/golang/go/issues/52911 but I don't think the use case for having access to the raw value was really explained.

One use case is to unminify HTML created by a templating engine, so that we can compare it to expected output, and have an easy to visualise result.

Part of that use case is to find issues like invalid escaping, so fixing the invalid input isn't what we want.

One option is to fork the HTML parser and make the change to add the raw attribute value to the Node type, and then use it. There's only about 1 commit a month to the parser, so it probably wouldn't be too much of a maintenance burden. https://github.com/golang/net/commits/master/html

**Comment by oliverpool** [comment]
> having access to the raw value was really explained

Actually getting the "value as interpreted by the browser" should be enough (which is what `a.Val` gives I think). Even if the string representation differ, if the browser interpretation is the same, then the code should be safe.

Alternatively, you could reconstruct an `html.Token` from an `html.Node` (with a `StartTagToken` type) and call the `t.String()` method on it (but it will still escape previously unescaped values).

**Comment by a-h** [comment]
Thanks, agreed. I've fixed this in https://github.com/a-h/htmlformat/commit/5bd994fe268e4d505a9793143fa85414c7d50887
